[package]
name = "execution-core"
version.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
hex.workspace = true
market-core = { path = "../market-core" }
rust_decimal.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
rust_decimal_macros = "1"
