import type { MobileActionInputDto, MobileWorkspaceDto } from "./index";
export type MobileActionType = "observe" | "tap" | "scroll_up" | "scroll_down" | "scroll_left" | "scroll_right" | "back" | "home" | "input_text" | "open_app" | "stop";
export interface MobileActionResult { actionId:string; actionType:MobileActionType; startedAt:string; completedAt?:string|null; status:"pending"|"running"|"completed"|"failed"|"cancelled";deviceId:string;beforeObservationId?:string|null;afterObservationId?:string|null;errorCode?:string|null;errorMessage?:string|null;triggeredBy:string }
export interface MobileUIElement { id:string;role:string;className:string;text?:string|null;contentDescription?:string|null;resourceId?:string|null;clickable:boolean;scrollable:boolean;editable:boolean;enabled:boolean;selected:boolean;bounds:{x:number;y:number;width:number;height:number};redacted:boolean }
export interface MobileAcquisitionObservation { id:string;deviceId:string;capturedAt:string;packageName:string;activityName:string;screenWidth:number;screenHeight:number;uiTreeHash:string;elementCount:number;elements:MobileUIElement[];source:"android_ui_tree";previousObservationId?:string|null;redactions:string[] }
export interface ObservationDiff { beforeObservationId:string;afterObservationId:string;changed:boolean;changeTypes:string[];addedElements:string[];removedElements:string[];changedElements:string[];summary:string }
export interface ExtractedMobileData {id:string;observationId:string;type:"visible_text"|"title"|"list_item"|"button"|"link_like_element"|"numeric_value"|"timestamp_like_text"|"status"|"selected_item";value:string;elementId:string;confidence:number;extractionMethod:"ui_tree"|"rule";capturedAt:string}
export interface MobileDataObject {id:string;sourceType:"android";deviceId:string;packageName:string;observationId:string;objectType:"text"|"list"|"metric"|"status"|"content"|"unknown";title?:string|null;content:string;values:Record<string,string|number|boolean>;capturedAt:string;deduplicationKey:string;provenance:{observationId:string;extractionMethod:"ui_tree"|"rule";elementIds:string[];activityName:string;extractedDataIds:string[]}}
export interface MobileCollectionWorkspace {observations:MobileAcquisitionObservation[];diffs:ObservationDiff[];actions:MobileActionResult[];dataObjects:MobileDataObject[];lastExtractionCount:number;lastNewObjectCount:number}
export interface MobileInteractionResponse {result:MobileActionResult;workspace:MobileWorkspaceDto}
export interface MobileDataProvenance {object:MobileDataObject;observation:MobileAcquisitionObservation;extractedData:ExtractedMobileData[];sightingCount:number}
export function mobileActionType(input:MobileActionInputDto):MobileActionType {switch(input.target.kind){case "tap":return "tap";case "swipe":return `scroll_${input.target.direction}`;case "type":return "input_text";case "back":return "back";case "home":return "home";case "open_app":return "open_app";}}
