import {describe,it,expect} from "vitest";
import {renderToStaticMarkup} from "react-dom/server";
import type {MobileCollectionWorkspace,MobileDataObject} from "@ordinconn/contracts";
import {filterMobileData,MobileDataStream,MobileObservationContext,MobileProvenanceDetail} from "./MobileCollectionPanels";
import {createTranslator} from "../i18n";
const collection:MobileCollectionWorkspace={observations:[],diffs:[],actions:[],dataObjects:[],lastExtractionCount:0,lastNewObjectCount:0};
const props={collection,t:createTranslator("en"),onExtract:async()=>{},onProvenance:async()=>{throw new Error("no source");},connected:false};
const object:MobileDataObject={id:"data-fixture",sourceType:"android",deviceId:"emulator-fixture",packageName:"com.android.settings",observationId:"obs-fixture",objectType:"metric",title:null,content:"42",values:{number:42},capturedAt:"2026-10-02T00:00:00Z",deduplicationKey:"fixture-hash",provenance:{observationId:"obs-fixture",elementIds:["el-fixture"],activityName:".Settings",extractionMethod:"rule",extractedDataIds:["extract-fixture"]}};
describe("manual mobile acquisition panels",()=>{
    it("renders exact source IDs and original UI evidence",()=>{const observation={id:"obs-fixture",deviceId:"emulator-fixture",packageName:"com.android.settings",activityName:".Settings",capturedAt:object.capturedAt,screenWidth:100,screenHeight:200,uiTreeHash:"hash",elementCount:1,elements:[{id:"el-fixture",role:"text",className:"TextView",text:"42",contentDescription:null,resourceId:"id/count",clickable:false,scrollable:false,editable:false,enabled:true,selected:false,bounds:{x:0,y:0,width:100,height:20},redacted:false}],source:"android_ui_tree" as const,redactions:[]};const html=renderToStaticMarkup(<MobileProvenanceDetail source={{object,observation,extractedData:[],sightingCount:2}} t={createTranslator("en")}/>);for(const value of ["emulator-fixture","obs-fixture","el-fixture",".Settings","id/count","Original UI evidence"])expect(html).toContain(value);});
    it("renders honest empty data and observation states",()=>{const html=renderToStaticMarkup(<><MobileDataStream {...props}/><MobileObservationContext {...props}/></>);expect(html).toContain("No collected data");expect(html).toContain("Observation context");expect(html).toContain("Observe a device first");expect(html).not.toContain("Agent plans");});
    it("filters only real objects and displays app, capture time and method",()=>{expect(filterMobileData([object],"metric")).toHaveLength(1);expect(filterMobileData([object],"text")).toEqual([]);expect(filterMobileData([object],"all")).toHaveLength(1);const html=renderToStaticMarkup(<MobileDataStream {...props} collection={{...collection,dataObjects:[object]}}/>);expect(html).toContain("com.android.settings");expect(html).toContain("42");expect(html).toContain("Rule from UI Tree");});
    it("shows terminal action errors without pretending collection succeeded",()=>{const c={...collection,actions:[{actionId:"a",actionType:"tap" as const,startedAt:"2026-10-02T00:00:00Z",status:"failed" as const,deviceId:"emulator-fixture",triggeredBy:"owner",errorCode:"DEVICE_DISCONNECTED"}]};const html=renderToStaticMarkup(<MobileObservationContext {...props} collection={c}/>);expect(html).toContain("DEVICE_DISCONNECTED");expect(html).toContain("failed");});
});
